[workspace]
authors = ["prefect-qc"]
channels = ["conda-forge", "bioconda"]
name = "prefect-qc"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "*"
fastqc = "*"
fastp = "*"
falco = "*"
multiqc = { version = "*", channel = "bioconda" }
pytest = "*"

[pypi-dependencies]
prefect = "*"
